### ISSUE TITLE
シナリオファイルの仕様書を書く

### ISSUE THREAD

**Issue by enjoysoftware** [enjoysoftware/gaming#5]
場面のタイトル名、テキスト、選択肢設定、音楽、背景へのパスで構成する

**Comment by r02092** [comment]
キャラクターの表示に関わること(画像ファイル名、位置、大きさ)とテキストを表示する速さも指定できるようにする
キャラクターの位置や大きさの設定は画像側で調整されてたら必要ないかもしれないけど。

**Comment by enjoysoftware** [comment]
画像側で調整した方がよい可能性大

**Comment by r02092** [comment]
まあそっちの方がシンプルな実装になるのでその方がいいかも。
商業ゲームでも割とそうらしいし。

**Comment by enjoysoftware** [comment]
@r02092 できたけどどう?

**Comment by r02092** [comment]
実際にどういう風に書かれるのかがイメージしづらいので、
試しにこの書き方でストーリーの最初の方とか書いてくれると分かりやすいかも。
後、`jump`にはJavaScriptファイルも指定できるようにしないと不便じゃないかなと思う。

**Comment by enjoysoftware** [comment]
今現在、2つ目のシナリオと仕様書を詳細にしている(明日に完成かな?)

**Comment by r02092** [comment]
この仕様だと`image`,`music`,`ch_speed`,`background`が同じファイル内で変えられなくなりそうだけどそれでいいのだろうか。
プログラマ以外の人にも意見を訊いた方がいいかと。

**Comment by enjoysoftware** [comment]
とりあえず書けたんでクローズで。またマイナー変更は挟むかもしれません
