### ISSUE TITLE
セーブ機能を実装する

### ISSUE THREAD

**Issue by r02092** [enjoysoftware/gaming#6]
以下のことについて考える
- 何を保存するか
- どういったデータの形式にするか
- どのようにしてデータを保持するか
### 何を保存するか
シナリオJSONファイルの名前とそのファイル内での位置を保存してセーブした位置から再開できるようにする
証拠品にIDをつけて、IDを記録することで手に入れた証拠品も記録する
"どのような人から聞こうか・・・","さて、どこへ行こうか・・・・","犯行をしていた時は・・・"で選択済みの選択肢も保存する(これらは同時に保存する必要がないので同じ場所に保存してもよい)
推理シーケンスで失敗した回数を記録する(失敗の回数でエンディングが分岐するため)
###  どういったデータの形式にするか
まだ考えていないが[`game/js/main.js`の`sdata`変数](https://github.com/enjoysoftware/gaming/blob/main/game/js/main.js#L59)がテスト用ではあるが手に入れた証拠品の記録に使われているので証拠品の記録関係はそれをベースにすると良さそう
### どのようにしてデータを保持するか
 `localStorage`を使う

**Comment by enjoysoftware** [comment]
あーなるほど。なかなかいいね。それとチート対策もしないと。

**Comment by r02092** [comment]
アクションゲームとかオンラインゲームとかじゃないからチート対策はいらないかなって思ったけどいるの?

**Comment by enjoysoftware** [comment]
一応なしでやって余裕があったらやろうか。

**Comment by enjoysoftware** [comment]
どうでもいいけど、データを保存するには多くの変数をグローバル化することが必要。グローバル汚染が増えそう。

**Comment by enjoysoftware** [comment]
セーブ機能の実装が終わったので課題点。
* 画像などもロード時に反映させる -> セーブデータに画像などのパスも記述
* セーブデータのロード後にEnterを押さないとロードが反映されない -> Enterのイベントを無理やり送信させればいいのか?
* slct関数の途中でロードが発生するとぐちゃぐちゃになる -> slct関数を強制停止できないのか?(←これちょっと不明)
* 証拠集めの途中の場合バグる -> ロード時に画像からイベントの消去が発生するので実装がややこしくなるsrvy関数が混乱する
