### ISSUE TITLE
証拠品のデータの作成とシナリオファイルとの連携

### ISSUE THREAD

**Issue by r02092** [enjoysoftware/gaming#9]
証拠品の確認の画面は既に完成しているがそこに表示するデータがまだできていない。
なのでデータを作成する必要がある。(ストーリーを書いた人に作ってもらった方がいいかも)
データの仕様については[`main.js`の30〜42行目](https://github.com/enjoysoftware/gaming/blob/main/game/js/main.js#L30)を参照。
シナリオの`text`の中に【】がある所で証拠品を取得したことになる。
シナリオの中の`】`の後ろに証拠品IDを記述するような感じを検討。(`】`は必ず末尾に来ているようなので。分かりにくかったら変える)
例えば、
`・・・進展だ。【謎の暗号を手に入れた。】`
の場合、
証拠品のデータは、
`["謎の暗号","「6C 11C 11A 2A 3A 1B 2E 10A 3C」と書いてある、なにかからちぎった跡のある紙"]`
のように書き、
証拠品IDが`7`の場合シナリオファイルには、
`・・・進展だ。【謎の暗号を手に入れた。】7`
のように書く。この`7`の部分は実際には表示されない。

**Comment by enjoysoftware** [comment]
シナリオファイルに付属のような感じで
~~~json
"evidence" : ["謎の暗号","「6C 11C 11A 2A 3A 1B 2E 10A 3C」と書いてある、なにかからちぎった跡のある紙",証拠ID]
~~~
のような感じで書いておき、シナリオファイルがジャンプしたときにプログラム側の配列に追記していく方式にしたほうが扱いはしやすいかも。それで一旦やってみる。

**Comment by r02092** [comment]
それも思ったけどセーブデータの容量が増えるかなって思って。
まあ大した容量じゃないしそっちの方が実装楽そうだからそっちでいいかな。
というかその方式だったら"証拠ID"は要らなくない?

**Comment by r02092** [comment]
結局、最初に書いたみたいに証拠品のデータは分けて書く形にした。
データの管理のこと考えたら複雑になりそうなので。

**Comment by enjoysoftware** [comment]
今自分もやって見てややこしくなったので最初のようにシナリオファイルにはevidence_idとevidence_stageだけ乗せておくようにする。
